const nodemailer = require("nodemailer");
const config = require("config");
const email = config.get("email");
const pw = config.get("password");

let transporter = nodemailer.createTransport({
  //   host: "jrajni6@gmail.com",
  //   port: 465,
  //   secure: true,
  service: "gmail",
  auth: {
    user: email,
    pass: pw,
  },
});

exports.send = function (data, callback) {
  let mailOptions = {
    from: '"AJNA LABS PRIVATE LIMITED" <...@ajna.ai>',
    to: "<...@ajna.ai>",
    subject: "Different Modules Analysis",
    text: "Report Generated by Ajna",
    attachments: [{ filename: "General Report.pdf", path: data }],
  };

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      return console.log(error);
      callback(false);
    }
    console.log("mail sent");
    // callback(true);
  });
};
